version: '3.3'

services:
  mysql:
    build: .
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ./volumes/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8090:80
    links:
      - mysql
    depends_on:
      - mysql
    env_file:
      - .env